name: Deploy GCP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

    build:
        name: Run Docker
        runs-on: ubuntu-latest
        environment: Test
        env:
          IMAGE_NAME: gcr.io/${{secrets.GCP_PROJECT_ID}}/${{vars.APP_NAME}}:latest
          ACCOUNT: ${{secrets.GCP_ACCOUNT_NAME}}@${{secrets.GCP_PROJECT_ID}}.iam.gserviceaccount.com
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - uses: space-wizards/submodule-dependency@v0.1.5
        - uses: snickerbockers/submodules-init@v4
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'
            
        - id: auth
          uses: 'google-github-actions/auth@v1'
          with:
              project_id: ${{secrets.GCP_PROJECT_ID}}
              credentials_json: ${{ secrets.GCP_CREDENTIALS }}
              service_account: $ACCOUNT
        
        - name: Setup Google SDK
          uses: google-github-actions/setup-gcloud@v1

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet
      
        - name: Build Docker Image
          run: docker build -t $IMAGE_NAME .

        - name: Push Docker Image
          run: docker push $IMAGE_NAME
         
        - name: Deploy Image 
          run: gcloud run deploy ${{secrets.GCP_PROJECT_ID}} --image $IMAGE_NAME --region us-central1
        
        - name: Update Service
          run: gcloud run services update ${{vars.APP_NAME}} --image $IMAGE_NAME --region us-central1
          
