name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

    deploy:

        name: Setup Docker
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
        steps:

        - name: Checkout repository
          uses: actions/checkout@v2
        - uses: space-wizards/submodule-dependency@v0.1.5
        - uses: snickerbockers/submodules-init@v4

        - name: Build Docker image
          run: docker build -t $IMAGE_NAME .

        - name: Test Docker image
          run: docker run $IMAGE_NAME

        - name: Push Docker image
          run: docker push $IMAGE_NAME
          
