name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: space-wizards/submodule-dependency@v0.1.5
    - uses: snickerbockers/submodules-init@v4
    - uses: dtolnay/rust-toolchain@nightly
    - uses: ikalnytskyi/action-setup-postgres@v4
    - name: Build
      run: cargo build --verbose
    - name: Run Tests
      run: cargo test --verbose
  build-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: space-wizards/submodule-dependency@v0.1.5
    - uses: snickerbockers/submodules-init@v4
    - uses: dtolnay/rust-toolchain@nightly
    - name: Build Release
      run: cargo build --verbose --release
  

